
GET http://127.0.0.1:1001/api/orgaos

###
POST http://127.0.0.1:1001/api/orgaos
Content-Type: application/json

{
  "descricao" : "SAAE IGUATU"
}


## Tipo Documento

###
GET http://127.0.0.1:1001/api/tipos-documentos

###
POST http://127.0.0.1:1001/api/tipos-documentos
Content-Type: application/json

{
    "descricao": "relatorio da gestao fiscal"
}


## Estante

###
GET http://127.0.0.1:1001/api/estantes

###
POST http://127.0.0.1:1001/api/estantes
Content-Type: application/json

{
    "descricao" : "Estante 3"
}

###
POST http://127.0.0.1:1001/api/estantes/1
Content-Type: application/json

{
    "descricao" : "Estante 1"
}

## Credores

###
GET http://127.0.0.1:1001/api/credores

###
POST http://127.0.0.1:1001/api/credores
Content-Type: application/json


{
   "nome" : "Vitor",
   "tipo_documento" : "cpf",
   "cpf" : "01299945303",
   "logradouro" : "Rua Padre Sá",
   "numero" : "356",
   "bairro" : "Centro",
   "cidade" : "Cedro",
   "cep" : "63400000",
   "e-mail" : "vitor.itarget@gmail.com",
   "telefone" : "88998554469",
   "banco" : "nubank",
   "agencia" : "10001",
   "conta" : "101231",
   "observacoes" : "Gosto muito de usar o sistema feito pelo vitor"
}
